-- MySQL Script generated by MySQL Workbench
-- Mon Jun 22 16:27:19 2020
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPTICA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPTICA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OPTICA` ;

-- -----------------------------------------------------
-- Table `OPTICA`.`PROVEIDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPTICA`.`PROVEIDOR` (
  `codi_ulleres` INT NOT NULL AUTO_INCREMENT,
  `codi_marca` INT NOT NULL,
  `nif_proveidor` VARCHAR(8) NOT NULL,
  `nom_proveidor` VARCHAR(45) NOT NULL,
  `carrer_proveidor` VARCHAR(255) NOT NULL,
  `ciutat_proveidor` VARCHAR(45) NOT NULL,
  `codipostal_proveidor` VARCHAR(45) NOT NULL,
  `telefon_proveidor` VARCHAR(45) NOT NULL,
  `fax_proveidor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codi_ulleres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPTICA`.`EMPLEATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPTICA`.`EMPLEATS` (
  `codi_empleat` INT NOT NULL AUTO_INCREMENT,
  `nom_empleat` VARCHAR(45) NOT NULL,
  `codi_client` INT NOT NULL,
  `num_factura` INT NOT NULL,
  PRIMARY KEY (`codi_empleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPTICA`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPTICA`.`CLIENTS` (
  `codi_client` INT NOT NULL AUTO_INCREMENT,
  `nom_client` VARCHAR(45) NOT NULL,
  `adreça_client` VARCHAR(45) NOT NULL,
  `tel_client` VARCHAR(20) NOT NULL,
  `mail_client` VARCHAR(45) NOT NULL,
  `dataregistre_client` VARCHAR(45) NOT NULL,
  `recomanacio_client` VARCHAR(45) NULL,
  `codi_ulleres` INT NOT NULL,
  `num_factura` INT NOT NULL,
  `codi_empleat` INT NULL,
  PRIMARY KEY (`codi_client`),
  INDEX `codi_empleat_idx` (`codi_empleat` ASC),
  CONSTRAINT `codi_empleat`
    FOREIGN KEY (`codi_empleat`)
    REFERENCES `OPTICA`.`EMPLEATS` (`codi_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPTICA`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPTICA`.`FACTURA` (
  `num_factura` INT NOT NULL AUTO_INCREMENT,
  `codi_client` INT NOT NULL,
  `codi_empleat` INT NOT NULL,
  PRIMARY KEY (`num_factura`),
  UNIQUE INDEX `num_factura_UNIQUE` (`num_factura` ASC),
  UNIQUE INDEX `codi_client_UNIQUE` (`codi_client` ASC),
  INDEX `codi_empleat_idx` (`codi_empleat` ASC),
  CONSTRAINT `codi_empleat`
    FOREIGN KEY (`codi_empleat`)
    REFERENCES `OPTICA`.`EMPLEATS` (`codi_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codi_client`
    FOREIGN KEY (`codi_client`)
    REFERENCES `OPTICA`.`CLIENTS` (`codi_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPTICA`.`MARQUES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPTICA`.`MARQUES` (
  `codi_marca` INT NOT NULL AUTO_INCREMENT,
  `nom_marca` VARCHAR(45) NOT NULL,
  `nif_proveidor` VARCHAR(8) NOT NULL,
  `codi_ulleres` INT NOT NULL,
  PRIMARY KEY (`codi_marca`),
  INDEX `codi_ulleres_idx` (`codi_ulleres` ASC),
  CONSTRAINT `codi_ulleres`
    FOREIGN KEY (`codi_ulleres`)
    REFERENCES `OPTICA`.`PROVEIDOR` (`codi_ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPTICA`.`ULLERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPTICA`.`ULLERES` (
  `codi_ulleres` INT NOT NULL AUTO_INCREMENT,
  `codi_marca` INT NOT NULL,
  `preu_ulleres` INT NOT NULL,
  `codi_client` INT NULL,
  `graduacio_esq` VARCHAR(45) NOT NULL,
  `graduacio_dret` VARCHAR(45) NOT NULL,
  `flotant` TINYINT(1) NOT NULL,
  `plastic` TINYINT(1) NOT NULL,
  `metall` TINYINT(1) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `num_factura` INT NULL,
  PRIMARY KEY (`codi_ulleres`),
  INDEX `num_factura_idx` (`num_factura` ASC),
  INDEX `codi_marca_idx` (`codi_marca` ASC),
  CONSTRAINT `num_factura`
    FOREIGN KEY (`num_factura`)
    REFERENCES `OPTICA`.`FACTURA` (`num_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codi_marca`
    FOREIGN KEY (`codi_marca`)
    REFERENCES `OPTICA`.`MARQUES` (`codi_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
